/**
 * This file consists of various constants for the smart Alerts module
 */
export default {
  smartAlerts: 'Alerts',
  staffType: 'Staff Type',
  staffId: 'Staff ID',
  building: 'Building',
  floor: 'Floor',
  department: 'Department',
  location: 'Location',
  tagID: 'Tag ID',
  StaffEvents: 'Events',
  alertType: 'Alert Type',
  escalateButton: 'Escalate',
  clearButton: 'Clear',
  applyButton: 'Apply',
  comment: 'Acknowledge the Alert',
  escalateOptions: {
    option1: 'I am away from the facility',
    option2: 'I need additional help',
    option3: 'Other',
  },
  ISDRAlertTypes: {
    tagOffline: 'Tag Offline',
    tagLowBattery: 'Tag Low Battery',
    staffEmergencyAlert: 'Staff Emergency Alert',
  },
  buttonsInnerText: {
    alerts: 'Alerts',
    tasks: 'Tasks',
    events: 'Events',
  },
  acknowledge: 'Acknowledge',
  paginationRange: '1 - 0 of 0',
  unacknowledged: 'Unacknowledge',
  createTask: 'Create Task',
  createButton: 'Create',
  tasks: 'Tasks',
  saveButton: 'Save',
  completeButton: 'Complete',
  tableView: 'Table View',
  sidePanel: 'Side Panel',
  carousel: 'Carousel',
  urlDataVerification: {
    smartAlerts: 'smartAlerts',
    alerts: 'alerts',
    events: 'events',
  },
  TaskDescription: 'createTasks',
  editTaskDescription: 'editCreatedTask',
  acknowledgedBy: 'Acknowledged By',
  noAlerts: "We couldn't find any matches for that",
}
