/*
 *Holds data like labels, urls segments, toast messages, confirmation messages, info card labels, button inner text, table column headers, alert types, modal titles, event, task, alert, task edit input, alert edit input, alert dropdown options
 */

import smartRules from './prosightAssets/smartRules'
import smartReports from './smartReports'

export default {
  urlText: {
    overviewDashboard: 'overviewDashboard',
    task: 'tasks',
    event: 'events',
    smartAlertManagement: 'smartAlerts',
    alerts: 'alerts',
    smartLocation: 'smartLocation',
    smartMonitoring: 'smartMonitoring',
    smartCompliance: 'smartCompliance',
    subModules: {
      permissioning: 'permissioning',
      users: 'users',
      oidc: 'oidc',
    },
    create: 'create',
    edit: 'users/edit',
    smartRules: 'smartRules',
    smartOperations: 'smartOperations',
  },
  toastMessages: {
    messageAfterTaskEdition: 'Task Description Updated Successfully',
    messageAfterTaskCompletion: 'Task Completed Successfully',
    messageAfterTwoTasksCompletion: '2 Tasks Completed',
    messageAfterTwoAlertsClear: '2 Alerts Cleared',
    messageAfterTwoAlertsAcknowledge: '2 Alerts Acknowledged',
    messageAfterInvalidDateRange: 'Invalid Date',
    messageAfterAlertAcknowledge: 'Alert Acknowledged Successfully',
    messageAfterTaskCreated: 'Task Created Successfully',
    messageAfterAlertClear: 'Alert Cleared Successfully',
    messageAfterEventUnacknowledge: 'Event Unacknowledged Successfully',
    escalateAlert: 'Alert Escalated Successfully',
    messageAfterAlertIsResolved : 'Alert Resolved Successfully',
    messageAfterRespondingToStaffEmergencyAlert : 'Alert marked as Responding',
  },

  infoCardLabel: {
    totalTasks: 'Total Tasks',
    tagTasks: 'Tag Tasks',
    sensorTasks: 'Sensor Tasks',
    gatewayTasks: 'Gateway Tasks',
    serverStatus: 'Server Status',
    totalAlerts: 'Total Alerts',
    tagAlerts: 'Tag Alerts',
    sensorAlerts: 'Sensor Alerts',
    gatewayAlerts: 'Gateway Alerts',
  },
  actionPlace: {
    tableView: 'Table View',
    sidePanel: 'Side Panel',
    carousel: 'Carousel',
    alertDetailsPage: 'Alert Details Page',
    mobile: 'Mobile',
  },
  buttonsInnerText: {
    smartAlertManagement: 'Alerts',
    permissioning: 'Permissioning',
    tasks: 'Tasks',
    alertText: 'Alerts',
    events: 'Events',
    cancel: 'Cancel',
    apply: 'Apply',
    complete: 'Complete',
    unacknowledge: 'Unacknowledge',
    acknowledge: 'Acknowledge',
    clear: '^Clear$',
    clearButton: 'Clear',
    save: 'Save',
    create: 'Create',
    editTask: 'Edit Task',
    completeTask: 'Complete Task',
    createTask: 'Create Task',
    completeButton: 'Complete',
    editTask: 'Edit Task',
    escalate: 'Escalate',
    comment: 'Comment',
    smartComplianceBtn: 'Smart Compliance',
    smartRules: 'Rules',
    smartReports: 'Reports',
    proPar: 'Pro Par',
    parLevelStaus: 'PAR Level Status',
    tileView: 'Tile View',
    standDown: 'Stand Down',
    responding : 'Responding',
    notResponding : 'Not Responding',
    monitoring: 'Monitoring'
  },
  tableColumnHeaders: {
    deviceId: 'Device ID',
    deviceType: 'Device Type',
    alertTypeHeader: 'Alert Type',
    createdBy: 'Created By',
    dateTime: 'Date/Time',
    building: 'Building',
    floor: 'Floor',
    location: 'Location',
    battery: 'Battery',
    acknowledgedDate: 'Acknowledged Date',
    eventLog: 'Event Log',
    acknowledgedBy: 'Acknowledged By',
    taskDescription: 'Task Description',
    assetTypes: 'Asset Type',
    assetIds: 'Asset ID',
    tagID: 'Tag ID',
    staffTypes: 'Staff Type',
    staffIds: 'Staff ID',
    department: 'Department',
    equipmentType: 'Equipment Type',
    sensorID: 'Sensor ID',
    assignedDepartment: 'Assigned Owner',
    complianceStatus: 'Compliance Status',
  },

  alertType: {
    alertType: 'Tag Low Battery < 5',
    alertTypePercentage: 'Tag Low Battery < 5%',
    alertTypeOnSearchbar: 'Tag Low Battery  5',
  },
  modalTitles: {
    editAlert: 'Edit Alert',
    completeTask: 'Complete Task',
    acknowledgeAlert: 'Acknowledge Alert',
    createTask: 'Create Task',
    clearAlert: 'Clear Alert',
  },
  event: {
    alertType: 'Tag Offline',
    deviceType: 'Asset Tag',
    eventLog: 'Alert',
  },
  task: {
    alertType: 'Tag Offline',
    deviceType: 'Asset Tag',
  },
  alert: {
    alertType: 'Tag Offline',
    deviceType: 'Asset Tag',
  },
  taskEditInput: 'SMARTHOSP-TC-6839',
  alertEditInput: 'SMARTHOSP-TC-6832',
  paginationRange: '1 - 0 of 0',
  alertDropdown: { options: ['Acknowledge', 'Clear', 'Create Task'] },
  module: {
    iap: 'iap',
  },
  acknowledge: 'Acknowledge',
  acknowledgeTitle: 'Acknowledge Alert',
  smartAlerts: 'Alerts',
  taskDescription: {
    updateTaskDescription: 'SMARTHOSP-8885',
    taskDescription: 'SMARTHOSP-8896',
  },
  acknowledgeDescription: 'SMARTHOSP-9058',
  uiText: {
    noTasks: 'No Tasks',
    noAlerts: 'No Alerts',
  },
  alertDetails: {
    assetName: 'assetName',
    tagOfflineAlert: 'tagOffline',
    assetId: 'assetId',
    assetType: 'assetType',
  },
  table: {
    assetTable: 'asset-alerts',
  },
  comments: {
    commentForTask: 'Task Created',
    commentForEditedTask: 'Task Edited',
    commentForAcknowledge: 'Alert Acknowledged',
  },
  typeOfTag: {
    assetTag: 'Asset Tag',
    staffTag: 'Staff Tag',
    sensorTag: 'Sensor',
  },
  popUps: {
    confirmationPopUpText: 'Acknowledging an Alert transitions it into an Event. You can view them in Events table.',
    clearAlertPopUp: 'Clearing an Alert will permanently remove it from the System. This action cannot be undone.',
  },
  pageFromWhereActionIsDone: {
    alertsPage: 'Alert',
    taskPage: 'Task',
  },
  escalateOptions: {
    option1: 'I am away from the facility',
    option2: 'I need additional help',
    option3: 'Other',
  },
  paneText: {
    acknowledgeAlertMessage: 'Acknowledging an Alert transitions it into an Event. Events cannot be viewed on the Mobile application.',
    createTaskMessage: 'Create a description for the new Task associated with this Alert.',
    clearAlertMessage: 'Clearing an Alert will permanently remove it from the System. This action cannot be undone.',
    editTaskMessage: 'Edit the task description associated with this Alert.',
    completeTaskMessage: 'Completing a Task transitions it into an Event. Events cannot be viewed on the Mobile application.',
  },
  escalatedTxt: 'Escalated',
  monitoring: {
    inspectEquipment: 'Inspect Equipment',
    inspect: 'Inspect',
    inspectEquipmentMessage: 'Do you want to proceed with inspecting the temperature for this equipment?',
    inspectionCompleteMessage: 'inspection completed',
    inpectionToastMessage: 'Equipment inspected',
    inpectionCompleteStatus: 'Inspection Complete'
  }

}
