/**
 *This comprises a selector for shared elements across various applications
 */
export default {
  profileSection: {
    userProfileBtn: "button[class*='topNavBar']",
  },
  tagTxt: 'tag',
  searchDepo: "input[placeholder='Search . . .']",
  sensorTxt: 'sensor',
  assetTxt: 'asset',
  equipmentTxt: 'equipment',
  staffTxt: 'staff',
  linkBtn: 'Link',
  saveBtn: 'button:contains("Save")',
  unlinkTagBtn: 'Unlink Tag',
  cancelButton: 'button:contains("Cancel")',
  overViewDashBoard: 'Overview Dashboard',
  systemAnalytics: 'System Analytics',
  userAnalytics: 'User Analytics',
  coxProsight: 'Cognosos',
  pageTitle: 'div[class*="text-pageTitle"]',
  title: 'div[class*="title"]',
  linkTag: 'button:contains("Link Tag")',
  sideNavTitle: 'div[class*="text-sideNavTitle"]',
  scrollBar: "div[aria-label='grid'][role='rowgroup']",
  button: "button[type='button']",
  clearButton: "button:contains('Clear')",
  createBtn: "button[type='submit']",
  confirmationPopup: "div[class*='text-dialogMessage']", //this will point for the confirmation message that usually comes before deleting anything or other operations like linking a tag
  dialogueDeleteBtn: "button[class*='button-dialogDelete']", //delete button inside confirmation dialogue box
  searchResultRowCell: "div[class*='TableV2-cell']", //this will point for the each cell of a row in a table
  resultRow: "div[class*='cell']", //this will point for the rows of table
  sideNavBtn: 'button[class*="secondaryNavBarToggle"]',
  sidePanelButtons: "div[class*='flex-sideNav']",
  editBtn: 'button[title="Edit"]',
  deleteBtn: 'button[title="Delete"]',
  sidePanel: 'div[class*="pane-detailCardContent"]',
  clearAllButton: 'button[title="Clear All"]',
  clearAllButtonMobile: 'button[class *= "ClearAll"]',
  backButtonInMobileView: 'button[class  *= button-mobileAssetHistoryNavBack]',
  dataRowInSidePanel: 'div[class*="dataBlock"]',
  confirmationBtnInConfirmationDialogue: 'button[class*="button-dialogConfirm"]',
  linkUnlinkScreenBackBtn: 'button[class*="button-assetHistoryHeaderBack"]',
  applicationMenuBtn: 'button[class*="toggleButton-applicationMenu"]',
  applicationMenuItem: 'button[class*="toggleButton-applicationMenuItem"]',
  searchBar: 'input[placeholder="Search"]',
  deleteButton: "button:contains('Delete')",
  radioButton : "input[class *= 'cypress-radio']",
  applicationBtnText: {
    Asset: 'Prosight Assets',
    Safety: 'Prosight Safety',
    Environment: 'Prosight Environment',
    Admin: 'Prosight Core',
  },
  buttonTag: 'button',
  divTag: 'div',
  labelTag: 'label',
  inputTag: 'input',
  spanTag: 'span',
  listTag: 'li',
  radioTypeInput: 'input[type=radio]',
  skip_CancelBtn: 'button[class*="button-dialogCancel"]',
  skipBtn: 'button:contains("Skip")',
  linkButton: "button[title='Link']",
  tagsCheckBox: 'input[type="checkbox"]',
  doneButton: "button[class*='button-detailCardStatusUpdate']",
  tableBody: 'div[class*="tableBody"]',
  dialogueCancel_ContinueBtn: 'button[class*="button-dialogCancel"]',
  deleteBtnText: 'Delete',
  clearSearchBtn: 'button[title="Clear Search"]',
  tagIdInput: 'input[placeholder="Enter Tag ID"]',
  sensorIdInput: 'input[placeholder="Enter Sensor ID"]',
  moduleBtnsText: {
    smartRules: 'Rules',
    smartReports: 'Reports',
    smartLocations: 'Smart Location',
    deviceManagement: 'Device Management',
    sensorManagement: 'Sensor Management',
  },
  filters: {
    hospitalFilter: 'button[class*="toggleButton-hospital"]', //same can be used for building filter
    availableDropDownOptions: 'div[class*="Popup-popup"]',
    options: "span[class*='title']", //each options
  },
  applicationButton: 'button[class*="toggleButton-applicationMenu"]',
  dropdownContainer: 'div[class*="popup"][class*="popup"]', // applicationContainer: 'div[class*="pane_"][class*="Pane-pane-"]',
  buildingButton: 'button[class*="toggleButton-building"]',
  buildingContainer: 'div[class*="pane"][class*="pane-filterPaneVariant"]',
  checkbox: 'input[type="checkbox"]',
  headerButtonToBack: 'button[class*="button-linkingScreenBack"]',
  pagination: {
    pagination: 'label[class*="label-paginationRange"]',
    paginationRange: 'label[class*="label-range"]',
  },
  clearFilterButton: 'button[class*="button-filterClear"]',
  applyButtonFilter: 'button[class*="button-filterApply"]',
  alias: {
    result_Row: 'resultRow',
    editButton: 'editBtn',
    delButton: 'delBtn',
  },
  buttonsInnerTxt: {
    clearButton: 'Clear',
  },
  applyBtn: 'button[class*="apply"]',
  cell: 'div[role="cell"]',
  rowInTable: 'div[role="row"][class*="row"]',
  closeButton: 'button:contains("Close")',
  smartLocation: {
    viewsContainer: 'div[class*="pane-viewToggles"]',
    tableViewButton: 'button[title="Table View"]',
    mapViewButton: 'button[title="Map View"]',
    dualViewButton: 'button[title="Dual View"]',
    viewOnMapButton: 'button[title="View on Map"]',
    historicalLogButton: 'button[title="Historical Log"]',
    endDateInput: 'input[placeholder="End Date"]',
  },
  accountSettings: {
    departmentInput: "input[name='department']",
    navbarButton: 'button[class*="toggleButton-topNavBar"]',
    settingsPopupItem: 'div[class*="popupItem"]',
    nameInput: 'input[name="name"]',
    emailInput: 'input[name="email"]',
    phoneNumberInput: 'input[name="phone"]',
    timeZoneDropdown: 'input[name="timeZone"]',
    timeZoneDropdownList: 'div[class *="rw-popup"] ul li',
    currentPasswordInput: 'input[name="currentPassword"]',
    newPasswordInput: 'input[name="newPassword"]',
    newPasswordConfirmInput: 'input[name="newPasswordConfirm"]',
    downloadButton: 'button[class*="button"][class*="button-secondary"] i[class*="ch-userManual"]',
    inputFeedbackMessage: 'div[class*="text-captionSmall"]',
    popup: 'div[class*="pane"]',
    sideNavButton: 'button[class *="toggleButton-sideNav"]',
    notificationSections: 'div[class *="grid"]',
    checkbox: 'div[class *="checkbox"]',
    checkboxLabel: 'div[class *="text-checkboxLabel"]',
    notificationRows: 'div[class *="pane_"][class *="caption"]',
    notificationTypeCheckboxLabel: 'label[class *="label-inputTitle"]',
    toggle: 'div[role *="checkbox"]',
    toggleButton: 'button[class *="toggleButton-toggle"]',
    startHourInput: 'input[placeholder="Select Start Time"]',
    endHourInput: 'input[placeholder="Select End Time"]',
    hoursDropdownButton: 'button[title ="Select time"]',
    hoursDropdownContainer: 'div[class*="rw-datetime-picker"] div[class*="rw-popup-container"]',
    hoursDropdownOptions: 'ul li[role="option"]',
    hoursPillButton: 'button[class*="button-pill"]',
    addHourButton: 'button[class*="button-add"]',
    notificationToggleLabel: 'label[class *="label-inputCaption"]',
    celsius: 'label:contains("Celsius")',
    fahrenheit: 'label:contains("Fahrenheit")',
    accountSettingPageContainer: 'div[class*="mobileSecondaryNav"]',
    allDaysToggleButton: "label:contains('All Days')",
    allHoursToggleButton: "label:contains('All Hours')",
    changePasswordDialogBox: "div[class*='deleteDialog']",
    logoutButton: 'button:contains("Logout")',
    logoutConfirmationBox: "div[class*='deleteDialog']",
    signInButton: 'button[type="submit"]',
  },
  moduleBtn: 'button[class*="toggleButton-sideNavBar"]',
  subModuleBtn: 'button[class*="toggleButton-sideNav"]',
  tableHeader: 'div[role="columnheader"]',
  hamburgerBtn: 'i[class*="fa-bars"]',
  cardView: 'div[class*="listItem"]',
  dropdownListbox: 'ul[role="listbox"]',
  lintButtonForMobileView: 'button[title="Link & Unlinking"]',
  linkTagOrSensor: 'div[item="link"]',
  unlinkTagOrSensor: 'div[item="unlink"]',
  linkAssetToTagBtn: 'Link Asset to Tag',
  popupTextDailogMessage: 'div[class*="text-dialogMessage"]',
  viewport: {
    desktop: 'desktop',
    mobile: 'mobile',
  },
  closeIconInMobile: 'button[class*=mobileCloseWindow]',
  mobileSecondarySideNav: 'div[class*=mobileSecondaryNav]',
  editIconBtn: 'i[class*="ch-edit"]',
  deleteIcon: 'i[class *= "ch-delete"]',
  detailsIcon: 'i[class*="ch-details"]',
  popupDialogBox: 'div[class*="pane-deleteDialog"]',
  selectBtn: 'button:contains("Select")',
  locationSelectionIcon: 'button[class*="button-locationSelection"]',
  dialogDropdown: 'button[class*=button-dialogMultiselect]',
  headerCard: 'div[class*="pane-mobileAssetHistoryHeaderCard"]',
  alertTypeBtn: 'button:contains("Alert Type")',
  sortOptionDialog: 'div[class*="pane-sortOptionsDialog"]',
  incidentContainer: 'div[class*="incidentContentArea"]',
  dropDown: ' div[class*="rw-dropdown"]',
  sidePanelCardHeader: 'div[class*= text-detailCardHeader]',
  searchBarOnDropdown: 'input[name="selectorFilter"]',
  popupContainer: 'div[class*="pane-dialog"]',
  innerButton: 'div[class *= "mobileNavGroups"]',
  bulkUploadSelectors: {
    bulkUploadButton: 'button[class *= "bulkImportImport"]',
    bulkUploadTitle: 'div[class *= "bulkUploadTitle"]',
    downloadCsvTemplate: 'button[class *= "bulkUploadDownload"]',
    bulkUploadTableTitle: "div[class *= 'text-dialogTitle']",
  },
  buildingdeselectParentClass: "div[class*='list-dialogMultiselect']",
  buildingdeselectClass: 'pane-dialogMultiselectSelected',
  applicationAccess: "div[class*='tether-element']",
}
