/**
 * This consists of page wise selectors of Safety application
 */

export default {
  moduleBtnsText: {
    //can chain this text for clicking any module button inside safety application
    staffManagementModule: 'Staff Management',
    tagManagement: 'Tag Management',
    staffTypePage: 'Staff Type',
    staffAssignment: 'Staff Assignment',
  },

  staffManagement: {
    linkTagBtnInConfirmationBox: 'button:contains("Link Tag")',
    skipLinkTagBtn: 'button:contains("Skip")',
    linkUnlinkBtn: 'button[title="Link / Un-link"]',
    linkTagOption: 'Link Tag(s)',
    unlinkTagOption: 'Unlink Tag(s)',
    unlinkTagBtn: 'button[title="Un-link"]',
    staffAndTagSection: 'div[class*="pane-pairingTableContainer"]',
    linkButton: "button[title='Link']",
    pairingTableHeader: 'div[class*="pane-pairingTableHeader"]',
    label_department: 'Assigned Department',
    searchStaff: 'input[placeholder="Search Staff"]',
    linkStaffToTagBtn: 'Link Staff to Tag',
    popupDialogBox: 'div[class*="pane-deleteDialog"]',
    searchFilter: 'input[class *="filterInput_qFYiN"]',
    staffAssignment: {
      addStaffMemberBtn: 'button[title="Create Staff Member"]',
      addStaffMemberBtnMobile: 'button[title="Add Staff Member"]',
      staffNameInputField: 'input[placeholder=" Enter Staff Name"]',
      staffIdInputField: 'input[placeholder=" Enter Staff ID"]',
      departmentInput: 'button[class*="cypress-selectassignedowner"]',
      staffTypeInput: 'button[class*="cypress-itemtype"]',
      dropDownForDepartmentAndStaffTypeInput: 'button[class*="toggleButton-inputSelector"]',
      linkButton: "button[title='Link']",
      doneButton: "button[class*='button-detailCardStatusUpdate']",
      emailInput: 'input[placeholder=" Enter Email Address"]',
      phoneNumberInput: 'input[placeholder=" Enter Phone Number"]',
      deleteStaffBtn: 'button:contains("Delete Staff")',
      createStaffTypeBtn: 'button:contains("Create Staff Type")',
      staffNameFieldError: 'div[name="data/name"]',
      staffIdFieldError: 'div[name="data/staffId"]',
      contactEmailFieldError: 'div[name="data/email"]',
      contactPhNoFieldError: 'div[name="data/phone"]',
    },
  },

  staffType: {
    addStaffTypeBtn: 'button[title="Add Staff Type"]',
    staffTypeNameInput: 'input[placeholder="Enter Staff Type"]',
    paginationRange: 'label[class*="label-range"]',
    defaultStaffIconText: 'Default',
    defaultSTaffIcon: 'i[class*="st-staff"]',
    nurseIcon: 'i[class*="st-nurse"]',
    physicianIcon: 'i[class*="st-physician"]',
    deleteStaffTypeBtn: 'button:contains("Delete Staff Type")',
    title: 'div[class*="title"]',
    staffTypeNameFieldError: 'div[name="name"]',
  },

  smartLocation: {
    acknowledgeButton: 'button[class*="button-ack"]',
    clearButtonInSidePanel: 'button[class*="button-clear"]',
    escalateButton: 'button[class*="escalateButton"]',
    incidentContainer: 'div[class*="incidentContentArea"]',
    escalateOptionsContainer: 'div[class*="pane-deleteDialog"]',
    escalateOption: 'div[class*="pane-radioDialog"]',
    enterComment: 'textarea[class*="textArea-textAreaDialog"]',
    incidentHeader: 'div[class*="incidentContentHeader"]',
    acknowledgeButtonInAlert: 'button[class*="acknowledgeStaffButton"]',
    unAcknowledgeButton: 'button[title="Unacknowledge"]',
  },

  smartAlerts: {
    labels: 'span[class *= "label"]',
    escalateButtonFromSidePanel: 'button[class *="button-escalate"]',
    searchBar: 'input[placeholder="Search"]',
    tagOfflineFilter: 'input[id="Tag Offline-option"]',
    searchBarOnFilter: 'input[placeholder="Search by..."]',
    filterLabels: 'div[class *= "label"]',
    tagLowBatteryFilter: 'input[id="Tag Low Battery-option"]',
    staffEmergencyFilter: 'input[id="Staff Emergency-option"]',
    tableTitle: 'div[class *= headerGroup_]',
    bulkSelect: 'button[title = "Select"]',
    selectActionDropDown: 'button[aria-label="open dropdown"]',
    selectOption: 'li[role = "option"]',
    clearButton: 'i[class *=ch-delete]',
    clearButtonOnPopUp: 'button[class *= button-dialogDelete]',
    acknowledgeFromSidePanel: 'i[class *= ch-check]',
    unAcknowledgeButton: 'button[title="Unacknowledge"]',
    unacknowledgedFromTable: 'button[class *= eventUnack]',
    unacknowledgedFromSidePanel: 'button[class *= unacknowledgeBtn]',
    unacknowledgedButtonOnPopup: 'button[class *= button-dialogConfirm]',
    sidePanelStaffName: 'div[class *= pane-detailCardHeader]',
    clearButtonOnFilter: 'button[class *= button-linkDestructive]',
    clearAlertFromSidePanel: 'button[class *=button-clear]',
    clearButtonOnTableView: 'li[class *= "rw-list-option"]',
    sidePanel: 'div[class *= pane-detailCardArea]',
    alertTypeInSidePanel: 'div[class *="alertTypeGeneral"]',
    taskDescription: 'div[class *= text-caption]',
    unacknowledgedFromTableForRoomOvercapacityAlert: 'button[class *= Unacknowledge]',
    unacknowledgedFromSidePanelForRoomOvercapacityAlert: 'button[class *= disabledButton]',
    noAlerts: 'div[class *= text-sectionTitle]',
    alertViewOnMap: 'button[class *= button-alertViewOnMap]',
    standDownButton : 'button[class *= standDown]',
    responsingButton : 'button[class *=respondingButton]',
    minimizeButton :'button[class *= minimize]',
    maximizeButton : 'i[class *="eq-maximiz"]',
    closeSidePanelButton :'button[class *= "detailCardClose"]',
    departmentToggleButton : 'div[name="isDepartmentAlerts"]',
    floorToggelButton : 'div[name="isFloorAlerts"]',
    checkbox : 'div[role="checkbox"]',
    ackInMobile : 'i[class *= ch-check]'
    
  },

  smartReports: {
    // createReportButton: 'button[class*="button-reportItem"]',
    addReportButtonInScheduledReports: 'button[class*= "cypress-safety.smartreports"]',
    //checkboxLabel: 'div[class*="checkboxLabel"]',
    //spanLabel: 'span[class*="label"]',
    reportTypeDropDown: 'div[class*= "cypress-safety.smartreports"]',
    scheduledEmailName: 'button[class *= button-filterPill]',
  },

  smartRules: {
    emailEscalationsInput: 'input[placeholder="Enter Email Address"]',
    numberEscalationsInput: 'input[placeholder="Enter Phone Number"]',
    searchInput: 'input[placeholder="Search"]',
    ruleNameInput: 'input[name="ruleName"]',
    roomMaximumRoomCapacityInput: 'input[name="threshold"]',
    ruleTypeDropdownBtn: 'button[class*="cypress-ruletype"]',
    ruleTypeDropdown: 'div[class*="cypress-ruletype"]',
    staffTypeDropdown: '.cypress-stafftype',
    departmentDropdown: '.cypress-department',
    locationDropdownLabel: 'label:contains("Location")',
    activityDropdownBtn: 'button[class*="cypress-activity"]',
    activityDropdown: 'div[class*="cypress-activity"]',
    alertDropDownBtn: 'button[class*="cypress-alert"]',
    alertDropDown: 'div[class*="cypress-alert"]',
    addRuleBtn: 'button[title="Add Rule"]',
    editRuleButton: 'button[title="Edit Rule"]',
    deleteRuleTableButton: 'button[title="Delete Rule"]',
    escalationHeader: 'div[class *= escalationHeader]',
  },

  escalations: {
    emailInputField: 'input[placeholder="Enter Email Address"]',
    phoneNumberInputField: 'input[placeholder="Enter Phone Number"]',
    clearAllBtn: 'button:contains("Clear All")',
    saveBtn: 'button:contains("Save")',
    setUpAutoEscalateBtn: 'div[class*="toggle"]',
    selectTimeFrameBtn: 'button:contains("Select Time Frame")',
    inputFilterPill: 'button[class*="button-escalationContact"]',
    email_ContactPillButton: 'button[class*="button-escalationContact"]',
  },
  sidePane: 'div[class*="pane-moduleNav"]',
}
