/**
 * This consists of page wise selectors of assets application
 */
export default {
  moduleButtons: 'button[class*="toggleButton-moduleNav"]',
  subModuleButton: 'button[class*="toggleButton-sideNav"]',
  assetsManagement: {
    navbar: 'i[class*="fa-fw"]',
    searchBar: 'input[placeholder="Search"]',
    searchButton: 'button[class*="button"]',
    createAssetButton: 'button[title*="Add Asset"]',
    departmentButton: "button[class*='cypress-selectassignedowner']",
    typeButton: "button[class*='cypress-itemtype']",
    dropdownContainer: 'div[class*="popup"][class*="popup"]',
    createAssetFields: 'div[class*="editor"]',
    nameInput: 'input[placeholder="Enter Asset Name"]',
    idInput: 'input[placeholder="Enter Asset ID"]',
    serialNumInput: 'input[placeholder="Enter Serial Number"]',
    typeInput: 'input[placeholder="Enter Asset Type]',
    manufacturerInput: 'input[placeholder="Enter Manufacturer Name"]',
    modelNumInput: 'input[placeholder="Enter Model Number"]',
    maintenanceDateDropdown: 'button:contains("Select Maintenance Invertal")',
    calenderBtn: 'button[title="Select date"]',
    maintenanceDateLabel: 'label:contains("Preventative Maintenance Interval")',
    nextMaintenanceDateInput: 'label:contains("Next Preventative Maintenance Due Date")+div',
    rentalDueDateLabel: 'label:contains("Rental Due Date")',
    rentalDateLabel: 'label:contains("Rented Date")',
    rentalDueClickOnRoight: 'span[class*="rw-i-chevron-right"]',
    rentalDateClickOnRight: 'span[class*="rw-i-chevron-right"]',
    rentalDateInput: 'input[name="data/rentalDueDate"]',
    rentalDetail: 'div[class*="radioButton"]',
    assetRow: 'div[role="row"]',
    createButton: 'button[type="Submit"]',
    assetCreatedDialog: 'div[class*="pane-deleteDialog"]',
    rentalOptionsDropdown: 'button[title="open dropdown"]',
    // edit
    hospitalButton: 'button[class*="toggleButton-hospital"]',
    assetDeleteDialog: 'div[class*="pane-deleteDialog"]',
    confirmDeleteButton: 'button[class*="button-dialogDelete"]',
    tableBody: 'div[role="table"]',
    linkButton: 'button[title="Link / Un-link"]',
    unlinkTagButton: 'button[title="Un-link"]',
    linkOptionsContainer: 'div[class*="popup"][class*="popup"]',
    pairingButton: 'button[class*="button-pairing"]',
    pairingTable: 'div[class*="pane-pairingTableSelection_"]',
    pairingTableHeader: 'div[class*="pane-pairingTableHeader"]',
    pairingTableContainer: 'div[class*="pane-pairingTableContainer"]',
    table: 'div[role="table"]',
    ownedLabel: 'label:contains("Owned")',
    rentedLabel: 'label:contains("Rented")',
    addAssetTypeButton: 'button[title="Add Asset Type"]',
    assetTypeInput: 'input[placeholder="Enter Asset Type"]',
    assetTypeIconButton: 'button[class*="toggleButton-assetTypeFormIcon"]',
    defaultIcon: 'i[class*="at-bed"]',
    cameraIcon: 'i[class*="at at-camera"]',
    thermometer: 'i[class*="at-thermometer"]',
    hoverMattIcon: 'i[class*="at-hovermatt"]',
    wheelChairIcon: 'i[class*="at-wheelchair"]',
    walkerIcon: 'i[class*="at-walker"]',
    rentalDetailLabel: 'label[class*="RadioButton-label"]',
    linkOptionsContainerForMobileview: 'div[class*=list-mobileLinkActionsDialog]',
    searchAsset: 'input[placeholder="Search Asset"]',
    deleteAssetBtn: 'button:contains("Delete Asset")',
    createAssetType: 'button:contains("Create Asset Type")',
    assetTypeNameFieldError: 'div[name="name"]',
  },
  smartLocation: {
    viewsContainer: 'div[class*="pane-viewToggles"]',
    tableViewButton: 'button[title="Table View"]',
    mapViewButton: 'button[title="Map View"]',
    dualViewButton: 'button[title="Dual View"]',
    viewOnMapButton: 'button[title="View on Map"]',
    historicalLogButton: 'button[title="Historical Log"]',
    backAssetHistoryButton: 'i[class*="chevronLeft"]',
    assetPaneHistory: 'div[class*="tabPane-assetHistory"]',
    mapBox: 'div[class*="mapboxgl-map"]',
    tableInHistory: 'div[role="rowgroup"]',
    dateFilterButton: 'button[class*="dateTimeRangePicker"]',
    dropdownDateButton: 'button[class*="rw-btn"]',
    listOfFilterDate: 'li[class*="rw-list-option"]',
    cardOnMapInHistory: 'div[class*="pane-historySelectionCard"]',
    locationInCard: 'div[class*="location"]',
    selectedRow: 'div[class*="selected"]',
    expandButton: 'button[class*="button-expand"]',
    startDateInput: 'input[placeholder="Start Date"]',
    endDateInput: 'input[placeholder="End Date"]',
    parentOfDropdownDateButton: 'div[class*="rangeType"]',
    mapCanvas: 'canvas[class*="mapboxgl-canvas"]',
    mapCanvas: 'canvas[class*="mapboxgl-canvas"]',
  },
  smartReports: {
    departmentLabel: 'label:contains("Assigned Department")',
    assetNameLabel: 'label:contains("Asset Name")',
    buldingLabel: 'label:contains("Building")',
    locationLabel: 'label:contains("Location")',
    plusIconButton: 'button[class*="cypress-assets.smartreports"]',
    reportTypeOptions: 'div[class*="cypress-assets.smartreports"]',
    reportTypeLabel: 'label:contains("Report Type")',
    reportTypeInput: 'button[class*="cypress-report"]',
    reportScheduleLabel: 'label:contains("Report Schedule")',
    dateRangeLabel: 'label:contains("Date Range")',
    dateRangeInput: 'input[placeholder="Start"]',
    startDateLabel: 'label:contains("Start Date")',
    stopDateLabel: 'label:contains("Stop Date")',
    timeLabel: 'label:contains("Time")',
    frequencyLabel: 'label:contains("Frequency")',
    openDropdownButton: 'button[title="open dropdown"]',
    assignedOwnerLabel: 'label:contains("Assigned Owner")',
    assignedDepartmentLabel: 'label:contains("Department")',
    assetTypeLabel: 'label:contains("Asset Type")',
    dropdownContainer: 'div[class*="rw-popup"]',
    reportNameInput: 'input[placeholder="Enter Report Name"]',
    emailInput: 'input[placeholder="Enter Email Address"]',
    previewReportBtn: 'button:contains("Preview Report")',
    downloadPreviewBtn: 'button:contains("Download Preview")',
    sendReportBtn: 'button:contains("Send Report")',
    scheduleReportBtn: 'button:contains("Schedule Report")',
    addButtonInEmail: 'button[class*="button-addContact"]',
    calendarButton: 'button[title="Select date"]',
    clockButton: 'button[title="Select time"]',
    titleInReport: 'div[class*="text-reportDialogTitle"]',
    sendNowLabel: 'label:contains("Send Now")',
    sendLaterLabel: 'label:contains("Send Later")',
    sendReportOnLabel: 'label:contains("Send Report On")',
    sendReportAtLabel: 'label:contains("Send Report At")',
    deleteButton: 'button[title="Delete Scheduled Report"]',
    sidePanelDeleteBtn: 'button[title="Delete Report Schedule"]',
    editButtonOnTableView: 'button[title="Edit Scheduled Report"]',
    editButtonOnSidePanel: 'button[title="Edit Report Schedule"]',
    timeOptionToClick: 'ul[aria-live="polite"]>li:first',
    startDateInput: 'input[placeholder="Start Date"]',
    endDateInput: 'input[placeholder="End Date"]',
    endDateInput: 'input[placeholder="End Date"]',
  },
  smartAlerts: {
    labels: 'span[class *= "label"]',
    tagOfflineFilter: 'input[id="Tag Offline-option"]',
    searchBarOnFilter: 'input[placeholder="Search by..."]',
    filterLabels: 'div[class *= "label"]',
    tagLowBatteryFilter: 'input[id="Tag Low Battery-option"]',
    criticallyUnderPARFilter: 'input[id = "Critically Under PAR-option"]',
    stockedOutFilter: 'input[id = "Stocked Out-option"]',
    underParFilter: 'input[id = "Under PAR-option"]',
    shrinkageFilter: 'input[id="Shrinkage-option"]',
    assetExitBuilding: 'input[id="Asset Exited Building-option"]',
    maintenanceDueFilter: 'input[id="Maintenance Due-option"]',
    rentalDueFilter: 'input[id="Rental Due-option"]',
    tableTitle: 'div[class *= headerGroup]',
    selectAllCheckbox: 'input[type = "checkbox"]',
    bulkSelect: 'button[title = "Select"]',
    selectActionDropDown: 'button[aria-label="open dropdown"]',
    selectOption: 'li[role = "option"]',
    clearButton: 'i[class *=ch-delete]',
    clearButtonOnPopUp: 'button[class *= button-dialogDelete]',
    acknowledgeFromSidePanel: 'i[class *= ch-check]',
    unacknowledgedFromTable: 'button[class *= eventUnack]',
    unacknowledgedFromSidePanel: 'button[class *= unacknowledgeBtn]',
    unacknowledgedButtonOnPopup: 'button[class *= button-dialogConfirm]',
    sidePanelAssetName: 'div[class *= pane-detailCardHeader]',
    clearButtonOnFilter: 'button[class *= button-linkDestructive]',
    commentForCreatingTask: 'textarea[placeholder="Enter Task Description (Required)"]',
    createTaskFromSidePanel: 'button[class *= button-createTaskAssets]',
    editTask: 'button[title="Edit"]',
    completeTaskFromSidePanel: 'button[class *= completeTaskBtn]',
    completeTaskFromTableView: 'button[class *= button-taskComplete]',
    taskCard: 'div[class *= alertCard]',
    clearAlertFromSidePanel: ' button[class *= button-clearAssets]',
    clearButtonOnTableView: 'li[class *= "rw-list-option"]',
    sidePanel: 'div[class *= pane-detailCardArea]',
    alertTypeInSidePanel: 'div[class *="alertTypeGeneral"]',
    taskDescription: 'div[class *= text-caption]',
    pageNavigationButton: 'button[class*="button-mobileNavTitle"]',
    alertDetailsIcon: 'i[class*="ch-details"]',
    alertDetailsContainer: "div[class*='mobileAssetHistoryHeaderCard']",
    textDescriptionContainer: "textarea[class*='textArea']",
    taskDescriptionOnSidePanel: "div[class *= 'text-caption']",
    completeTaskFromTableView: "button[class *= 'button-taskComplete']",
  },
  smartRules: {
    addRule: 'button[title = "Add Rule"]',
    ruleNameField: 'input[placeholder="Enter Rule Name"]',
    roomTypeField: 'button[class *="cypress-roomtype"]',
    roomTypeSearchField: 'input[class *="filterInput"]',
    assetTypeSearchField: 'input[placeholder="Search Asset Type"]',
    cancelButton: 'button[class *= "button-secondary"]',
    missingRadioButton: 'div[class *= "cypress-missing"]',
    availableRadioButton: 'div[class *= "cypress-available"]',
    operationalRadioButton: 'div[class *= "cypress-operational"]',
    maintenanceRadioButton: 'div[class *= "cypress-maintenancereq"]',
    cleaningRadioButton: 'div[class *= "cypress-cleaningreq"]',
    inMaintenanceRadioButton: 'div[class *= "cypress-inmaintenance"]',
    outOfCirculationRadioButton: 'div[class *= "cypress-outofcirculation"]',
    naRadioButton: 'div[class *= "cypress-n/a"]',
    utilizedRadioButton: 'div[class *= "cypress-utilized"]',
    notUtilizedRadioButton: 'div[class *= "cypress-notutilized"]',
    lostRadioButton: 'div[class*= "cypress-lost"]',
    utilizationFactor: 'input[name="utilizationFactor"]',
    shrinkageWindow: 'input[name="shrinkageWindow"]',
    ruleNameOnSidePanel: 'div[class *= "headerTitle"]',
    labelOnSidePanel: 'div[class *= "label"]',
    sidePanel: 'div[class*="smartRulesCard"]',
    editRule: 'button[title="Edit Rule"]',
    deleteRule: 'button[title = "Delete Rule"]',
    parThreshold: 'input[placeholder="Select PAR Level Value"]',
    underPar: 'input[placeholder="Select Under PAR Value"]',
    overPar: 'input[placeholder="Select Over PAR Value"]',
    criticallyUnderPar: 'input[placeholder="Select Critically Under PAR Value"]',
    selectBuilding: 'button[class *= "cypress-building "]',
    selectAssetType: 'button[class *= "cypress-assettype "]',
    selectDepartment: 'button[class *= "cypress-department "]',
  },
  proPar: {
    assetTyperow: "div[role='row']:has(div[role='cell'])",
    parLevelStatusButton: 'button[class*="cypress-parlevelstatus"]',
    departmentButton: 'button[class*="cypress-department"]',
    roomTypeButton: 'button[class*="cypress-roomtype"]',
    favoritesContainer: 'div[class*="favoritesContainer"]',
    favoritesContentArea: 'div[class*="favoritesContentArea"]',
    tileCardView: 'div[class*="tileCardView"]',
    showDetails: 'div[class*="showDetails"]',
    proParassetTypes: 'div[class*="proParassetTypes"]',
    wrongIcon: 'i[class*="ch-closePropar"]',
    graphIcon: 'i[class*="tileIcon"]',
    assetTypeInGraph: 'div[class*="itemTypeLevel"]',
  },
  overviewdashboard: {
    ParLevelStatus: 'div[class*="proParBarChart"]',
    allstatus: 'div[class*="VictoryContainer"]',
    idsofstatus: 'text[id*="chart-bar-3-labels"]',
  },
}
