/**
 * This object consists of selector of environment application
 */
export default {
  moduleButtonText: {
    equipmentManagement: 'Equipment Management',
    smartMonitoring: 'Monitoring',
    envReport: 'Environmental Report',
    equipmentAssignment: 'Equipment Assignment',
    sensorManagement: 'Sensor Management',
    equipmentType: 'Equipment Type',
    smartMonitoringUrl: 'smartMonitoring',
  },
  equipmentManagement: {
    label_equipmentType: 'Equipment Type',
    label_building: 'Building',
    label_floor: 'Floor',
    label_departMent: 'Assigned Department',
    label_owner: 'Assigned Owner',
    label_rentalDetails: 'label:contains("Rental Details")',
    label_location: 'label:contains("Location")',
    label_calibrationDueDate: 'Calibration Due Date',
    label_Rented: 'Rented',
    label_Owned: 'Owned',
    label_assignedOwner: 'Assigned Owner',
    label: 'label[class*=label]',
    linkUnlinkBtn: 'button[title="Link / Un-link"]',
    linkSensorOption: 'Link Sensor(s)',
    linkSensorConfirmationBtn: 'button:contains("Link Sensor")',
    unlinkSensorOption: 'Unlink Sensor(s)',
    unlinkSensorBtn: 'Unlink Sensor',
    linkUnlinkPopup: 'div[class*="popupItem"]',
    unlinkTagBtn: 'button[title="Un-link"]',
    pairingTableHeader: 'div[class*="pane-pairingTableHeader"]',
    searchEquipment: 'input[placeholder="Search Equipment"]',
    equipmentNameFieldError: 'div[name="data/name"]',
    equipmentIDFieldError: 'div[name="data/equipmentId"]',
    minTempFieldError: 'div[name="data/range/temperature/operatingMin"]',
    maxTempFieldError: 'div[name="data/range/temperature/operatingMax"]',
    equipmentAssignment: {
      addNewEquipmentBtn: ' button[title="Create Equipment"]',
      addNewEquipmentBtnMobile: 'button[title="Add Equipment"]',
      equipmentNameInput: 'input[placeholder="Enter Equipment Name"]',
      equipmentIdInput: 'input[placeholder="Enter Equipment ID"]',
      manuFactureNameInput: 'input[placeholder="Enter Manufacturer Name"]',
      modelNumberInput: 'input[placeholder="Enter Model Number"]',
      lastCalibrationDateInput: 'input[name="data/calibration/date"]',
      minimumTemInput: 'input[placeholder="Enter Minimum Temperature"]',
      maximumTempInput: 'input[placeholder="Enter Maximum Temperature"]',
      radioBtnContainer: 'div[class*="radioButton_"]',
      rentalDueDateInput: 'input[name="data/rentalDueDate"]',
      equipmentTypeDropdown: 'button[class*="cypress-itemtype"]',
      buildingDropdown: 'button[class*="cypress-selectbuilding"]',
      floorDropdown: 'button[class*="cypress-selectfloor"]',
      assignedOwnerDropdown: 'button[class*="cypress-selectassignedowner"]',
      locationDropdown: 'button[class*="cypress-selectlocation"]',
      deleteEquipmentBtn: 'button:contains("Delete Equipment")',
      deleteEquipmentTypeBtn: 'button:contains("Delete Equipment Type")',
      linkEquipmentToSensorBtn: 'button:contains("Link Equipment to Sensor")',
      searchEquipment: 'input[placeholder="Search Equipment"]',
      createEquipmentTypeBtn: 'button:contains("Create Equipment Type")',
      equipmentTypeFieldError: "div[name='name']",
      bulkUpload: "div[class *= 'text-dialogTitle']",
      fileNameForBulkImport: 'div[class *= "text-body"]',
    },
    equipment_type: {
      addEquipmentTypeBtn: 'button[title="Add Equipment Type"]',
      equipmentTypeNameInput: 'input[placeholder="Enter Equipment Type"]',
      genericEquipmentTypeIconText: 'Default',
      genericIconClass: 'i[class*="eq-default"]',
      blanketWarmerIcon: 'i[class*="eq-blanketWarmer"]',
      freezerIcon: 'i[class*="eq-freezer"]',
      fluidBathIcon: 'i[class*="eq-fluidBath"]',
    },
  },
  smartAlerts: {
    sensorOfflineFilter: 'input[id="Sensor Offline-option"]',
    acknowledgeComment: 'textarea[class *= textArea]',
    acknowledgeTitle: 'div[class *=text-dialogTitle]',
    sensorLowBatteryFilter: 'input[id="Sensor Low Battery-option"]',
    calibrationDueIn5DayFilter: 'input[id="Calibration Due in 5 days-option"]',
    calibrationDueIn10DayFilter: 'input[id="Calibration Due in 10 days-option"]',
    calibrationDueIn30DayFilter: 'input[id="Calibration Due in 30 days-option"]',
    calibrationDueIn60DayFilter: 'input[id="Calibration Due in 60 days-option"]',
    rentalDue: 'input[id="Rental Due-option"]',
    inspectionDue: 'input[id="Inspection Overdue-option"]',
    temperatureWarning: 'input[id="Temperature Warning-option"]',
    temperatureOutRange: 'input[id="Temperature Out of Range-option"]',
    humidityOutOfRange: 'input[id="Humidity Out of Range-option"]',
    labels: 'span[class *= "label"]',
    searchBar: 'input[placeholder="Search"]',
    searchBarOnFilter: 'input[placeholder="Search by..."]',
    filterLabels: 'div[class *= "label"]',
    tableTitle: 'div[class *= headerGroup]',
    selectAllCheckbox: 'input[type = "checkbox"]',
    bulkSelect: 'button[title = "Select"]',
    selectActionDropDown: 'button[aria-label="open dropdown"]',
    selectOption: 'li[role = "option"]',
    clearButton: 'i[class *=ch-delete]',
    clearButtonOnPopUp: 'button[class *= button-dialogDelete]',
    acknowledgeFromSidePanel: 'i[class *= ch-check]',
    unacknowledgedFromTable: 'button[class *= eventUnack]',
    unacknowledgedFromSidePanel: 'button[class *= unacknowledgeBtn]',
    unacknowledgedButtonOnPopup: 'button[class *= button-dialogConfirm]',
    sidePanelEquipmentName: 'div[class *= pane-detailCardHeader]',
    clearButtonOnFilter: 'button[class *= button-linkDestructive]',
    commentForCreatingTask: 'textarea[placeholder="Enter Task Description (Required)"]',
    createTaskFromSidePanel: 'button[class *= button-createTaskAssets]',
    editTask: 'button[title="Edit"]',
    completeTaskFromSidePanel: 'button[class *= completeTaskBtn]',
    taskCard: 'div[class *= alertCard]',
    clearAlertFromSidePanel: ' button[class *= button-clearAssets]',
    clearButtonOnTableView: 'li[class *= "rw-list-option"]',
    sidePanel: 'div[class *= pane-detailCardArea]',
    alertTypeInSidePanel: 'div[class *="alertTypeGeneral"]',
    taskDescription: 'div[class *= text-caption]',
    escalateButton: 'button[class*="escalateButton"]',
    incidentContainer: 'div[class*="incidentContentArea"]',
    escalateOptionsContainer: 'div[class*="pane-deleteDialog"]',
    escalateButtonFromSidePanel: 'button[class*="button-escalate"]',
    acknowledgeButtonInAlert: 'button[class *= "acknowledgeButton"]',
    enterComment: 'textarea[class*="textArea-textAreaDialog"]',
    completeTaskFromTableView: 'button[class *= button-taskComplete]',
    escalateBtn: 'button:contains("Escalate")',
    carouselMinimizeIcon: 'i[class*="eq-minimize"]',
  },
  smartReports: {
    equipmentTypeLabel: 'label:contains("Equipment Type")',
    equipmentNameLabel: 'label:contains("Equipment Name")',
    plusIconButton: 'button[class*="cypress-environment.smartreports"]',
    reportTypeDropDown: 'div[class*="cypress-environment.smartreports"]',
    reportOptions: 'span[class*="title"]',
    reportScheduleList: 'ul[class*="rw-list"]',
    reportScheduleListOptions: 'li[role*="option"]',
    reportDropDownInReportForm: 'div[class*="cypress-report"]',
    radioButtonsContainer: 'div[class*="radioButton"]',
  },
  smartRules: {
    escalationHeader: 'div[class*="escalationHeader"]',
    addRule: 'button[title="Add Rule"]',
    cancelButton: 'button[class *= "button-secondary"]',
    searchEquipmentTypeSelector: 'input[placeholder="Search Equipment Type"]',
    searchEquipmentNameSelector: 'input[placeholder="Search Equipment Name"]',
    monitoredMinTemp: 'input[name="data/range/temperature/min"]',
    monitoredMaxTemp: 'input[name="data/range/temperature/max"]',
    optimalMinTempSelector: 'input[name="data/range/temperature/optimalMin"]',
    optimalMaxTempSelector: 'input[name="data/range/temperature/optimalMax"]',
    humidityMin: 'input[name="data/range/humidity/min"]',
    humidityMax: 'input[name="data/range/humidity/max"]',
    returnButton: 'button:contains("Return")',
    row: 'div[role="rowgroup"]',
    equipmentNameSidePanel: 'div[class*="text-detailCardHeader"]',
    deleteButtonOnEditPage: 'button:contains("Delete")',
    frequency: 'button[class *= "cypress-frequency"]',
    startTime: 'button[class *= "cypress-starttime"]',
    toggleButton: 'div[class *= handle]',
    secondInspctionToggel: 'div[name="secondInspection"]>div[class*="background"]',
    subtitle: 'div[class *= "text-subtitle"]',
    day: 'button[class *= "cypress-day"]',
    searchBarOnDropdown: 'input[name="selectorFilter"]',
    checkedItems: 'div[class *= "checkedItem"]',
  },
  monitoring: {
    inspectButton: 'button[title="Inspect Equipment"]',
    inspectEqpTitle: 'div[class *=text-dialogTitle]',
    inspectEqpDialogMessage: 'div[class*=text-dialogMessage]',
    inspectComment: 'textarea[class *= textArea]'
  }
}
