/**
 * This consists of page wise selectors of core application
 */
export default {
  moduleBtnText: {
    floorPlanManagementText: 'Floor Plan Management',
    floors: 'Floors',
    departments: 'Departments',
    roomType: 'Room Type',
  },
  hospitalManagementPageSel: {
    createHospitalButton: "button[title='Create Facility']",
    hospitalManagementButton: "span[class *= 'label']",
    detailSidePanel: "div[class*='pane-smartLocationDetailCard']",
    tableRow: 'div[role=row]',
    editButton: "i[class *= 'ch-edit']",
    cancelDialogButton: "button[type='button'].button-dialogCancel",
    cancelButton: "button[type='button']",
    saveButton: "button[type='submit']",
    nameInputField: "input[name='hospitalName']",
    nameInputFieldError: "div[name='hospitalName']",
    stateDropdown: "span[title = 'Select State']",
    popupItems: "div[class*='popupItem']",
    timeZoneDropdowns: "div[class*='rw-dropdown-list']",
    hospitalDropdowns: 'span:contains("Select Time Zone")',
    streetAddressInput: "input[name='streetAddress']",
    cityInput: "input[name='city']",
    zipInput: "input[name='zipCode']",
    applicationsCheckbox: "input[type='checkbox']",
    contactNameInput: "input[name='contactName']",
    contactEmailInput: "input[name='contactEmail']",
    searchInput: "input[placeholder='Search']",
    deleteButton: "i[class *= 'ch-delete']",
    deleteFormButton: "button i[class *= 'ch-delete']",
    confirmActionDialogButton: "button[type='button'].button",
    canNotDeleteMessage: "div[class *= 'text-dialogMessage']",
    phoneNumberInput: 'input[placeholder="Enter Phone"]',
    deleteDialogBox: 'div[class*="deleteDialog"]',
    hospitalTableScrollContainer: "div[aria-label='grid'][role='rowgroup']",
    hidHospital : "div[role='checkbox']"
  },

  buildingManagementPageSel: {
    tableScroll: 'div[class *="ReactVirtualized__Grid"][class *="tbody"]',
    createHospital: 'button[title="Create Hospital"]',
    createBuilding: 'button[title="Add Building"]',
    buildingManagementButton: "span[class = 'label']",
    hospitalManagementTabs: "button[class *='toggleButton-sideNav'] span[class *= 'label']",
    detailSidePanel: "div[class*='pane-smartLocationDetailCard']",
    table: 'div[role=table]',
    tableRow: 'div[role=row]',
    editButton: "i[class *= 'ch-edit']",
    deleteButton: "button[type='button'] i[class *= 'ch-delete'] ",
    cancelDialogButton: "button[type='button'].button-dialogCancel",
    cancelButton: "button[type='button']",
    saveButton: "button[type='submit']",
    nameInputField: "input[name='data/name']",
    buildingNameInput: "input[placeholder= ' Enter Building Name']",
    nameInputFieldError: "div[name='data/name']",
    dropdowns: '.rw-dropdown-list',
    popupItems: "div[class*='cypress-state']",
    buildingNameInput: "input[placeholder=' Enter Building Name']",
    stateDropdown: "span[title = 'Select State']",
    streetAddressInput: "input[placeholder=' Enter Street Address']",
    cityInput: "input[placeholder=' Enter City Name']",
    zipInput: "input[placeholder=' Enter Zip Code']",
    contactNameInput: "input[placeholder=' Enter Contact Name']",
    contactEmailInput: "input[placeholder=' Enter Email Address']",
    contactPhoneNumberInput: "input[placeholder=' Enter Phone Number']",
    searchInput: "input[placeholder='Search']",
    searchButton: "button[type='button'] .label", //Ask because its eq(10)
    confirmActionDialogButton: "button[type='button'].button.button-dialogDelete",
    cancelActionDialogButton: "button[type='button'].button.button-dialogCancel",
  },
  deviceManagementPageSel: {
    deviceManagementButton: "i[class *= 'ch-deviceManagement']",
    addTagButton: "button[title='Add Tag'] i",
    tagIdTextField: "Input[name='data/uniqueDeviceId']",
    tagTypeDropDown: "button[class *= 'toggleButton-selector'] ",
    manufacturerDropDown: "button[class *= 'toggleButton-selector'] ",
    modelDropDown: "button[class *= 'toggleButton-selector'] ",
    createButton: "button[type='submit']",
    searchBar: "input[placeholder='Search']",
    scrollBar: "div[aria-label='grid'][role='rowgroup']",
    editButton: "button[title='Edit'] i",
    ModelLabel: "label[class*='label']",
    saveButton: "button[type='submit']",
    deleteButton: 'i[class *= "ch ch-delete"]',
    cancelButton: 'button[class *= "button-secondary_"]>span[class *= "label"] ',
    deleteButtonOnPopup: 'button[class *= "button-dialogDelete"] ',
    tagIdInSidePanel: 'div[class *= pane-detailCardHeader]',
    sidePanel: "div[class *= 'pane-detailCardArea']",
    sidePanelLabels: 'div[class *= label]',
    sidePanelCloseButton: 'button[class *= "button-detailCardClose"]',
    tagsTable: 'div[role = row]',

    sensorManagementButton: 'button[class *= "toggleButton-sideNav"]>span[class *="label"]',
    addSensor: "button[title='Add Sensor'] i",
    sensorId: "input[placeholder='Enter Sensor ID']",
    sensorAndManufacturerDropdown: "button[class *= 'cypress-manufacturer ']",
    sensorModelName: "input[name = 'data/model']",
    sensorTable: 'div[class *= "row"]',
    deleteButtonOnSidePanel: "button[title = 'Delete']",
    editButtonOnSidePanel: "i[class *=  'ch-edit']",
    sensorTypeDropdown: "button[class *= 'cypress-sensortype ']",

    gatewayManagementButton: "button[class *= 'toggleButton-sideNav']>span[class *='label']",
    addGateway: "button[title='Add Gateway'] i",
    gatewaySid: "input[placeholder='Enter Gateway SID']",
    gatewayType: "button[class *='cypress-gatewaytype ']",
    buildingDropdown: "button[class *= 'cypress-selectbuilding']",
    floorDropdown: "button[class *= 'cypress-selectfloor']",
    locationDropdown: "button[class *= 'cypress-selectlocation']",

    unassignGateway: "button[title='Unassign']",
    gatewayName: "input[placeholder='Enter Gateway Name']",
    gatewayPolicyName: "input[placeholder='Enter Gateway Policy']",
    gatewayPolicyNameForKontakt: "input[placeholder='Enter Location Policy']",
    scroll: "div[class *=  'area_']",
    Labels: 'span[class *= label_]',
    buildingLabel: "div[class *= 'rw-dropdown-list-input']",
    gatewayCancelButton: "button[class *= 'button-secondary_']>span[class *= 'label']",
    gatewayTypeLabel: "label[class *='label-inputTitle']",
    gatewayTable: 'div[class *="even"]',
    gatewayDropdownOptions: 'div[class *= checkedItem]',
    tableView: "button[title= 'Table View']",

    addHhSensor: "button[title='Add HH Sensor']",
    manufacturer: "button[class *= 'cypress-manufacturer']",
    hhSensorIdSel: "input[placeholder='Enter HH Sensor ID']",
    hhSensorTypeSel: "button[class *='cypress-hhsensortype']",
    hhSensorNameSel: "input[placeholder='Enter HH Sensor Name']",
    hhSensorPolicySel: "input[placeholder='Enter HH Sensor Policy']",
    manualDispenseCountSel: "input[placeholder='Enter Dispenser Count']",
    buildingSel: "button[class *= 'cypress-selectbuilding']",
    floorSel: "button[class *= 'cypress-selectfloor']",
    nameInSidePanel: "div[class *= 'text-detailCardHeader']",
    sensorTypeSel: "span[class *= 'title']",
    unassignHHSensorInSidePanel: 'i[class *="ch ch-unlink"]',
  },
  smartAlertsSel: {
    staffManagementButton: 'button[class *= "toggleButton-moduleNav"]>span[class *="label"]',
    createStaff: "button[title='Create Staff Member'] i",
    staffName: "input[placeholder=' Enter Staff Name']",
    staffId: "input[placeholder=' Enter Staff ID']",
    staffManagementDropDown: "button[class *= 'toggleButton-selector']",
    submitButton: "button[type='submit'] span",
    linkTagButton: 'button[class *= "button-dialogConfirm"]',
    linkTagCheckBoxWindow: "div[class *= 'body2']",
    linkTagCheckBox: "div[class *= 'row']>div[role = 'cell']>div[class *='checkbox']>input[type = 'checkbox']",
    linkButton: "button[title='Link'] i",
    labels: 'span[class *= label]',
    comment: "textarea[class *= 'textArea']",
    sidePanels: 'div[class *= pane-detailCardArea]',
    alertTypeInSidePanel: 'div[class *= alertTypeGeneral]',
    createTaskFromSidePanel: 'button[class *= createTaskAssets]',
    commentInSidePanel: 'div[class *= comment]',
    taskDescriptionInSidePanel: 'div[class *= text-caption]',
  },
  floorPlanManagement: {
    floorPageFilter: 'button[class *= "cypress-floor"]',
    searchBarInFilter: 'input[placeholder = "Search . . ."]',
    centerOnItemBtn: 'button[title="Center on Items"]',
    sideMenuOptionBtns: 'button[class *= "toggleButton-sideNav"]',
    departmentBoundary: 'Department Boundaries',
    rooms: 'Rooms',
    departments: 'Departments',
    mapSettings: 'Map Settings',
    roomType: 'Room Type',
    pagination: 'label[class*="label-paginationRange"]',
    saveBtn: "button[class*='button-primary']",
    save: 'Save',
    cancelButton: 'Cancel',
    zoomOutBtn: 'button[title="Zoom Out"]',
    navBar: 'button[class*="secondaryNavBarToggle"]',
    floors: {
      addFloorBtn: "button[title='Add Floor']",
      hospitalNameInputField: "input[name='hospital']",
      buildingNameDropDownBtn: "button[class*='cypress-building']",
      buildingListOptions: 'li[role="option"]',
      buildingInputField: "input[name='building']",
      floorNameInputField: "input[name='floorName']",
      floorNumberInputField: "input[name='floorNumber']",
      uploadFloorPlanBtn: 'button:Contains("Upload Floorplan")',
      floorPlanUploadField: "input[type='file']",
      fileUploadWindowHeader: 'div[class *="iconLayout"]',
      selectedFloorPlanFileName: "div[class*='text-body']",
      continueBtn: 'Continue',
    },

    departmentBoundariesSel: {
      addDepartmentBoundaryBtn: 'button[title="Add Department Boundary"]',
      instructionsDialogueBox: 'div[class*="text-subtitle"]',
      boundaryNameColumnHeading: 'Boundary Name',
      canvasElem: 'canvas[class="mapboxgl-canvas"]',
      confirmLocationDiv: 'div[class*="text-dialogTitle"]',
      confirmBtn: "button[class*='button-dialogConfirm']",
      boundaryNameInput: 'input[placeholder="Enter Boundary Name"]',
      departmentDropDownBtn: 'Select Department',
      tableViewBtn: 'button[title="Table View"]',
      mapViewBtn: 'button[title="Map View"]',
      dualViewBtn: 'button[title="Dual View"]',
      editDepartBoundaries: 'button[title="Edit Department Boundaries "]',
      cancelbtn : 'button[class *= "cancel"]'
    },
    roomTypePageSel: {
      addRoomTypesBtn: 'button[title="Add Room Type"]',
      roomTypeNameInput: 'input[placeholder="Enter Room Type"]',
      roomTypeColorOptions: "button[class*='colorSample']:enabled",
      paginationRange: 'label[class*="label-range"]',
    },
    departmentsSel: {
      addDepartmentBtn: "button[title='Add']",
      departmentNameInput: 'input[placeholder="Enter Department Name"]',
    },
    roomsPageSel: {
      mapNameColumnHeading: 'Map Label',
      createRoom: 'button[title="Create Room"]',
      editRoomBtn: 'button[title="Edit Room"]',
      mapLabelInput: 'input[placeholder="Enter Map Label"]',
      mapLocationInput: 'input[placeholder="Enter Map Location"]',
      selectRoomType: 'Select Room Type',
      selectAssignedDepartMent: 'Select Department',
      floorFilter: 'button[class *= cypress-floor]',
      floorList: 'div[class *= filterOptionList]',
      popUp:'div[class *= popupItem]',
      buildingDropdown: 'label[class *= label]'
    },
  },
  userManagementSel: {
    userRoleButton: 'button[class*="toggleButton-actions"]',
    userRoleButtonInInvite: 'button[title="open dropdown"]',
    userRoleLabel: 'label[class*="label-inputTitle"]:contains("User Role")',
    userRoleList: '.rw-popup-container',
    moduleContainer: "div[class*='pane'][class*='grid']",
    roleOption: 'div[class*="popupItem"]',
    roleOptionInInvite: 'li[role="option"]',
    moduleHeader: 'div[class*="text][class*="text-subtitleCheckboxLabel"]',
    checkboxInModuleContainer: "div[class*='checkbox'] > input[type='checkbox']",
    users: {
      createButton: "button[class*='toggleButton-actionsBar']",
      departmentDropdown: "label:contains('Department (Optional)') + button[class*='toggleButton-inputSelector']",
      hospitalDropdown: "label:contains('Facility(s)') + button[class*='toggleButton-inputSelector']",
      dropdownList: "div[class*='popup_']",
      createUserButton: "button[class*='toggleButton-actionsBar']",
      usersPopUp: "div[class^='popupItem'][class*='Popup-item-']",
      passwordInput: "input[name='password']",
      deleteButton: "button[title='Delete User']",
      emailInvite: {
        hospitalDropdown: "label:contains('Facility') + button[class*='toggleButton-inputSelector']",
        inviteUserButton: 'button[type="Submit"]',
        addEmailButton: "button[class*='button-addContact']",
        createUserButtonInHeader: "div[class*='pane-formHeader'] > button[class*='button-tertiary']",
        emailInput: 'input[placeholder="Enter Email Address"]',
      },
      // edit fields
      editButton: "button[title='Edit User']",
      saveAfterEdit: 'button[type="Submit"]',
      userRow: "div[role*='row']",
      sidePanelButtons: "div[class*='pane-detailCardArea']",
      emailInput: 'input[placeholder="Enter Email"]',
      phoneInput: 'input[placeholder="Enter Phone"]',
      nameInput: 'input[placeholder="Enter Name"]',
      usernameInput: 'input[placeholder="Enter Email or Unique Username"]',
      userRoleInput: 'input[name="role"]',
      searchInput: 'input[placeholder="Search"]',
      deleteButtonDialog: 'button[class*="button-dialogDelete"]',
      cancelButtonDialog: 'button[class*="button-dialogCancel"]',
      editUserButtonInHeader: "button[class*='button-tertiary']:contains('Edit User')",
      // filter function
      buildingFilterButton: 'button[class*="toggleButton-building_"]',
      filterButtons: 'button[class*="toggleButton-secondaryFilters_"]',
      filterContainer: 'div[class*="pane-rootEditorFooter"]',
      applyButton: 'button[class*="button-filterApply"]',
      pillsContainer: 'div[class*="pillsContainer"]',
      secondaryPillsButton: 'button[class*="toggleButton-secondaryFilterPills"]',
      secondaryPillsContainer: 'div[class*="popup"][class*="popup"]',
      secondaryPillRowFilter: 'div[class*="popupItem_"][class*="item"]',
      applyButtonFilter: 'button[class*="button-primary"]',
      checkboxInFilter: 'input[type="checkbox"]',
      filterRow: 'div[class*="labelHolder"]',
      buttonPillFilter: 'button[class*="button-filterPill"]',
      columnFilterButtons: 'button[class*="toggleButton-tableFilter"]',
      clearAllButton: 'button[class*="button-filterPillClear"]',
      // bulk function
      bulkButton: 'button[title="Import Users"]',
      bulkDownloadButton: 'button[class*="button-bulkUploadDownload"]',
      primaryButton: 'button[class*="button-primary"]',
      resultingMessageInBulk: 'div[class*="text-dialogTitle"]',
      inputFile: 'input[type="file"]',
      userRoleLabel: 'label[class*="label-inputTitle"]:contains("User Role")',
      userRoleInput: 'input[name="role"]',
      pagination: 'label[class*="label-perPage"]',
    },
  },
  smartAlertsManagementSel: {
    tableBody: 'div[role="rowgroup"].ReactVirtualized__Grid',
    table: 'div[role="table"]',
    tableRow: 'div[role="rowgroup"].ReactVirtualized__Grid div[role="row"]',
    tableBulkCheckbox: 'div[role="rowgroup"].ReactVirtualized__Grid div[role="row"] input[type="checkbox"]',
    tableCell: 'div[role="table"] div[role="cell"]',
    lastTableCell: '.bodyCell_WI2D3:last-child',
    tableColumnHeader: 'div[role="columnheader"]',
    tableHeaderFilterPopup: 'div[class*= "popup_"]',
    tableClearAllFiltersButton: "button[title='Clear All']",
    tableHeaderFilterPopupSearchInput: 'div[class *="popup"] input[placeholder="Search by..."]',
    tableHeaderFilterPopupCheckbox: 'div[class *="checkbox"]',
    tableHeaderPopupOptionLabel: 'div[class *="pane-tableFilter"] label',
    searchInput: 'input[placeholder="Search"]',
    dateRangePickerButton: 'div[class *="text-dateRangeLeftIcon"]',
    dateRangeStartInput: 'input[placeholder="Start Date"]',
    dateRangeEndInput: 'input[placeholder="End Date"]',
    tableEditButton: 'div[role="rowgroup"].ReactVirtualized__Grid button[title="Edit"]',
    tableCompletedButton: 'div[role="rowgroup"].ReactVirtualized__Grid button[title="Complete"]',
    sidePanel: 'div[class *="pane-detailCardContent_"]',
    alertCloseSidePanel: 'div[class *="pane-detailCardContent"] button i[class *= "ch-close"]',
    modal: 'div[class*="pane_"][class*="pane-deleteDialog"]',
    modalTaskInput: 'textarea[placeholder="Enter Task Description"]',
    modalAlertInput: 'textarea[placeholder="Enter Comment"]',
    informationCards: 'div[class *="containerFlex" ] div[class *="card_" ]',
    informationCardsData: 'div[class *="containerFlex" ] div[class *="card" ] div[class *="value" ]',
    bulkAction: '.ch-bulkSelect',
    unacknowledgeSidePanelButton: 'div[class*="pane-detailCardArea"] button[class *="unacknowledgeBtn"]',
    tableUnacknowledgeButton: 'button[title="Unacknowledge"]',
    tableAlertActionDropdown: 'div[role="rowgroup"].ReactVirtualized__Grid div[role="row"] div[role="cell"] button[title="open dropdown"]',
    tableAlertActionDropdownOptions: 'div[role="rowgroup"].ReactVirtualized__Grid div[role="row"] div[role="cell"] ul[role="listbox"]',
    userActions: 'div[class*="userActionsContainer"]',
  },
  general: {
    moduleButton: 'button[type="button"]',
  },
  setupWizard: {
    facilityNameOnStep2: 'input[name="data/hospital/id"]',
    checkBox: 'div[class *= circleDone]',
    setupWizardButtonLabel: 'i[class *= "ch-setupWizard"]',
    streetAddressInput: 'input[placeholder=" Enter Street Address"]',
    cityInput: 'input[placeholder=" Enter City Name"]',
    zipCodeInput: 'input[placeholder=" Enter Zip Code"]',
    contactNameInput: 'input[placeholder=" Enter Contact Name"]',
    contactEmailInput: 'input[placeholder=" Enter Email Address"]',
    contactNumberInput: 'input[placeholder=" Enter Phone Number"]',
    facilityNameOnStep3: 'input[placeholder = "Enter Facility Name"]',
    buildingNameOnStep3: 'button[class *= cypress-building]',
    nextButtonOnPopup: 'button[class *= okay]',
    confirmButton: 'button[class *= button-dialogConfirm]',
    boundaryNameInput: 'input[placeholder="Enter Boundary Name"]',
    assignedOwnerInput: 'button[class *=cypress-selectassignedowner]',
    manufacturerDropdownInput: "button[class *= 'cypress-manufacturer'] ",
    createButtonOnStep6: "button[type='submit']",
    userRole: 'button[class *=  toggleButton-inputSelector]',
    hospitalNameOnStep6: 'input[name="hospitalIds"]',
    completeIcon: 'img[alt="complete"]',
    searchBarOnAssignedOwner: 'input[name="selectorFilter"]',
    footer: 'div[class *= pane-formButtons]',
    createRoom: 'button[title="Create Room"]',
  },
}
