export default {
  smartAlerts: 'Alerts',
  equipmentType: 'Equipment Type',
  building: 'Building',
  floor: 'Floor',
  assignedDepartment: 'Assigned Owner',
  location: 'Location',
  sensorID: 'Sensor ID',
  equipmentEvents: 'Events',
  alertType: 'Alert Type',
  clearButton: 'Clear',
  applyButton: 'Apply',
  acknowledge: 'Acknowledge',
  acknowledgeTitle: 'Acknowledge Alert',
  acknowledgeComment: 'Alert is Noted',
  paginationRange: '1 - 0 of 0',
  escalate: 'Escalate',
  unacknowledged: 'Unacknowledge',
  createTask: 'Create Task',
  createButton: 'Create',
  tasks: 'Tasks',
  saveButton: 'Save',
  completeButton: 'Complete',
  tableView: 'Table View',
  sidePanel: 'Side Panel',
  carousel: 'carousel',
  urlDataVerification: {
    alerts: 'alerts',
    events: 'events',
    tasks: 'tasks',
    smartMonitoring: 'smartMonitoring',
  },
  TaskDescription: 'createTasks',
  editTaskDescription: 'editCreatedTask',
  acknowledgedBy: 'Acknowledged By',
  comment: 'Comment',
  escalateOptions: {
    option1: 'I am away from the facility',
    option2: 'I need additional help checking on this equipment',
    option3: 'Other',
  },
}
