export default {
  GatewayManagementButton: 'Gateway Management',
  hhSensorManagementButtonText: 'HH Sensor Management',
  tagManagement: 'Tag Management',
  tags: 'Tags',
  sensors: 'Sensors',
  gateways: 'Gateways',
  hhSensors: 'Hand Hygiene Sensors',
  ManufacturerDropdownLabel: 'Select Manufacturer',
  GatewayTypeLabel: 'Select Gateway Type',
  FloorLabel: 'Select Floor',
  locationURL: 'location',
  locationLabel: 'Select Location',
  SensorManagementButton: 'Sensor Management',
  SensorTypeLabel: 'Select Sensor Type',
  GatewayLabel: 'Gateway Type',
  TagTypeDropdown: 'Select Tag Type',
  ModelDropdown: 'Select Model',
  ModelLabel: 'Model',
  tagTypeLabel: 'Tag Type',
  ManufacturerLabel: 'Manufacturer',
  DateConnected: 'Date Connected',
  EmptyValue: '-',
  sensorTypeLabel: 'Sensor Type',
  GatewayName: 'Gateway Name',
  GatewayPolicy: 'Gateway/Location Policy',
  Building: 'Building',
  Floor: 'Floor',
  Location: 'Location',
  label: {
    associatedLocationLabel: 'Associated Location',
    manual: 'Manual',
    automatic: 'Automatic',
    hid: 'HID',
    kontakt: 'Kontakt',
  },
  GatewayToastMessages: [
    'Gateway Created Successfully',
    'Gateway Details Updated Successfully',
    'Gateway Deleted Successfully',
    'Gateway Unassigned',
  ],
  SensorToastMessages: ['Sensor Created Successfully', 'Sensor Details Updated Successfully', 'Sensor Deleted Successfully'],
  TagToastMessages: ['Tag Created Successfully', 'Tag Details Updated Successfully', 'Tag Deleted Successfully'],
  gatewayManagementUrl: 'gatewayManagement',
  deviceManagementUrl: 'deviceManagement',
  overViewDashboardUrl: 'overviewDashboard',
  adminTable: 'admin',
  sidePanel: 'sidePanel',
  tableView: 'tableView',
  editPage: 'editPage',

  buttonInnerText: {
    hhSensorManagement: 'HH Sensor Management',
    sensorManagement: 'Sensor Management',
    gatewayManagement: 'Gateway Management',
  },
  urlText: {
    hhSensorManagementUrl: 'hhSensorManagement',
  },
  confirmationMessages: {
    unAssignHhSensorConfirmation:
      'Unassigning a Hand Hygiene Sensor will permanently remove it’s association to the defined location. You can assign it to a location by editing Location Details. This action cannot be undone.',
    deleteHhSensorConfirmation: 'Deleting a HH Sensor will permanently remove all associated data from the System. This action cannot be undone.',
    unableToDeleteHhSensor: 'This HH sensor cannot be deleted as it is assigned to a room.\n Please unassign the HH sensor before deleting it.',
  },
  toastMessages: {
    messageAfterUnAssignHhSensor: 'Hand Hygiene Sensor Unassigned',
    messageAfterHhSensorDeletion: 'Hand Hygiene Sensor Deleted Successfully',
    messageAfterHhSensorCreation: 'HH Sensor Created Successfully',
    messageAfterEditingHhSensor: 'HH Sensor Details Updated Successfully',
    messageAfterTagCreation: 'Tag Created Successfully',
    messageAfterEditingTag: 'Tag Details Updated Successfully',
    messageAfterDeletingTag: 'Tag Deleted Successfully',
    messageAfterSensorCreation: 'Sensor Created Successfully',
    messageAfterEditingSensor: 'Sensor Details Updated Successfully',
    messageAfterDeletingSensor: 'Sensor Deleted Successfully',
    messageAfterGatewayCreation: 'Gateway Created Successfully',
    messageAfterEditingGateway: 'Gateway Details Updated Successfully',
    messageAfterDeletingGateway: 'Gateway Deleted Successfully',
    messageAfterUnassignGateway: 'Gateway Unassigned',
  },
}
