export default {
  setupWizardButton: 'Setup Wizard',
  getStarted: 'Get Started',
  nextButton: 'Next',
  previousButton: 'Previous',
  hospital: 'Hospital',
  save: 'Save',
  cssProperties: {
    pointerEvents: 'pointer-events',
    noValue: 'none',
  },
  FacilityManagementModuleLink: 'Facility Management Module',
  FloorPlanManagementModuleLink: 'Floor Plan Management Module',
  SensorButton: 'Sensors',
  GatewayButton: 'Gateways',
  completeButton: 'Complete',
  createButton: 'Create',
  DeviceManagementModuleLink: 'Device Management Module',
  UserManagementModuleLink: 'User Management Module',

  urls: {
    urlOnStep2: 'hospitalManagement/buildings',
    urlOnStep3: 'floorPlanManagement',
    urlOnTags: 'tagManagement',
    urlOnSensor: 'sensorManagement',
    urlOnGateway: 'gatewayManagement',
    urlOnUsers: 'users',
  },
  userRole: 'Select User Role',
  testAdmin: 'Test Admin',
  geoJSONFilePath: 'cypress/fixtures/prosightCore/floorPlan.geojson',
  geoJSONFile: 'floorPlan.geojson',
  toastMessages: {
    messageAfterBuildingCreation: 'Building Created Successfully',
    messageAfterFacilityCreation: 'Facility created',
    messageAfterFloorCreation: 'Floor Created Successfully',
    messageAfterTagCreation: 'Tag Created Successfully',
    messageAfterSensorCreation: 'Sensor Created Successfully',
    messageAfterGatewayCreation: 'Gateway Created Successfully',
    messageAfterUserCreation: 'User Created Successfully',
  },
}
