export default {
  smartAlerts: 'Alerts',
  assetType: 'Asset Type',
  assetId: 'Asset ID',
  building: 'Building',
  floor: 'Floor',
  location: 'Location',
  tagID: 'Tag ID',
  AssetEvents: 'Events',
  alertType: 'Alert Type',
  clearButton: 'Clear',
  applyButton: 'Apply',
  IAPAlertTypes: {
    tagOffline: 'Tag Offline',
    tagLowBattery5: 'Tag Low Battery < 5',
    tagLowBattery20: 'Tag Low Battery 20',
    maintenanceDue: 'Maintenance Due',
    shrinkage: 'Asset Exited Building',
    rentalDue: 'Rental Due',
    criticallyUnderPar: 'Critically Under PAR',
    underPar: 'Under PAR',
    stockedOut: 'Stocked Out',
  },
  acknowledge: 'Acknowledge',
  noAlerts: 'No Alerts',
  paginationRange: '1 - 0 of 0',
  unacknowledged: 'Unacknowledge',
  createTask: 'Create Task',
  createButton: 'Create',
  tasks: 'Tasks',
  saveButton: 'Save',
  completeButton: 'Complete',
  tableView: 'Table View',
  sidePanel: 'Side Panel',
  AlertsToastMessage: {
    acknowledgingAlert: 'Alert Acknowledged Successfully',
    unacknowledgingAlert: 'Event Unacknowledged Successfully',
    creatingTask: 'Task Created Successfully',
    completingTask: 'Task Completed Successfully',
    editingTask: 'Task Description Updated Successfully',
    clearingAlert: 'Alert Cleared Successfully',
  },
  urlDataVerification: {
    alerts: 'alerts',
    events: 'events',
    tasks: 'tasks',
    smartAlerts: 'smartAlerts',
    smartLocation: 'smartLocation',
  },
  buttonsInnerText: {
    alerts: 'Alerts',
    tasks: 'Tasks',
    events: 'Events',
  },
}
