/**
 * This file consists on various constants for the assetsManagement module
 */
export default {
  urlText: {
    assetsAssignment: 'assetAssignment',
    assetsManagement: 'assetManagement',
    edit: 'edit',
    smartLocation: 'smartLocation',
    assets: 'assets',
    delete: 'delete',
    assetsType: 'assetType',
    tagManagement: 'tagManagement',
  },
  buttonsInnerText: {
    createAssetTypeButton: 'Create Asset Type',
    assetType: 'Asset Type',
    assetsAssignment: 'Asset Assignment',
    assetsManagement: 'Asset Management',
    searchButton: 'Search',
    delete: 'Delete',
    building: 'Building',
    unLinkTags: 'Unlink Tag(s)',
    linkTag: 'Link Tag(s)',
    unlinkTag: 'Unlink Tag',
    core: 'Prosight Core',
    apply: 'Apply',
    assets: 'Prosight Assets',
    tagManagement: 'Tag Management',
    department: 'Department',
    assignedDep: 'Assigned Owner',
    status: 'Status',
    assetsType: 'Asset Type',
    tagStatus: 'Tag Status',
    tagModel: 'Tag Model',
    tagManuf: 'Tag Manufacturer',
    assetName: 'Asset Name',
    selectAssignedOwner: 'Select Assigned Owner',
  },
  toastMessages: {
    assetCreated: 'Asset Created Successfully',
    editedAsset: 'Asset Details Updated Successfully',
    deletedAsset: 'Asset Deleted Successfully',
    tagLinked: 'Linked Successfully',
    tagUnLinked: 'Unlinked Successfully',
    assetTypeCreated: 'Asset Type Created Successfully',
    assetTypeDeleted: 'Asset Type Deleted Successfully',
    assetTypeEdited: 'Asset Type Updated Successfully',
    deletedTag: 'Tag Deleted Successfully',
  },
  paneText: {
    createdAsset: 'Asset was successfully created. Do you want to link a tag to the added asset?',
    deleteAsset: 'Deleting an Asset will permanently remove all associated data from the System. This action cannot be undone.',
    notFoundMatch: "We couldn't find any matches for that",
    cannotDeleteAsset: 'This asset cannot be deleted as it is linked to a tag. Please unlink the asset before deleting it.',
    unlinkingTag: 'Unlinking Tag from will stop tracking of the Assets. How do you wish to proceed?',
    messageUnlinkingTag: (assetName, tagName) =>
      `Unlinking Tag ${tagName} from ${assetName} will stop tracking of the Assets. How do you wish to proceed?`,
    deleteTypeAsset: 'Deleting an asset type will permanently remove all associated data from the System. This action cannot be undone.',
    deleteTag: 'Deleting a Tag will permanently remove all associated data from the System. This action cannot be undone.',
    cannotDeleteTag: 'This tag cannot be deleted as it is linked to an asset. Please unlink the tag before deleting it.',
  },
  dataOptions: {
    rented: 'Rented',
    iap: 'iap',
    minPagination: 10,
    minPagForSmallTables: 4,
    linked: 'Linked',
    unlinked: 'Unlinked',
    owned: 'Owned',
    rented: 'Rented',
    assetType: 'Asset Type',
    assetAssignment: 'Asset Assignment',
  },
  actionTypes: {
    default: 'default',
    fromCreate: 'fromCreate',
    linkTag: 'linkTag',
    unlinkTag: 'unlinkTag',
  },
  headers: {
    linkedAssetsTable: 'Linked Assets and Tags ',
    tags: 'Tags',
    assets: 'Assets',
    backToAssetsList: 'Back to Assets List',
  },
  keyNameOfTestData: {
    assetType: 'assetType',
    dep: 'department',
    status: 'status',
    manufacturer: 'manufacturer',
    tagModel: 'tagModel',
    assetName: 'assetName',
  },
  viewport: {
    desktop: 'desktop',
    mobile: 'mobile',
  },
  application: {
    iap: 'asset',
  },
  errorMessagesForAssetAssignmentPage: {
    assetNameExistsErrMsg: 'Asset name already exists',
    assetIdExistsErrMsg: 'Asset ID already exists',
  },
  errorMessagesForAssetTypePage: {
    assetTypeNameExistsErrMsg: 'Asset Type Already Exists',
    invalidAssetTypeNameErrMsg: 'Enter a valid asset type',
  },
  bulkImportConstants: {
    bulkImportTitle: 'Bulk Create Assets',
    assetBulkCsvPath: 'cypress/fixtures/prosightAssets/bulkImportAssets.csv',
    csvFileName: 'bulkImportAssets.csv',
  },
}
